Repository Let-s-intern/lets-intern-client, pull requests merged in 2024-06, with the labels that each got.

#557 [#553] 프로그램 페이지 개편
  public/icons/checkbox-fill.svg
  public/icons/checkbox-unchecked.svg
  public/icons/chevron-left-duo.svg
  public/icons/chevron-left-filled.svg
  public/icons/chevron-right-filled.svg
  public/icons/close-md.svg
  public/icons/filter.svg
  public/icons/play.svg
  public/icons/program-all.svg
  public/icons/program-challenge.svg
  public/icons/program-class.svg
  public/icons/program-detail.svg
  public/icons/redo.svg
  public/icons/skip-next-filled.svg
  public/icons/skpe-previous-filled.svg
  public/images/banner-example.png
  public/images/home/program-cell.png
  public/images/home/program-thumbnail.png
  src/Router.tsx
  src/components/common/home/regacy/section/ProgramSection.tsx
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/filter/FilterCheckbox.tsx
  src/components/common/program/filter/FilterItem.tsx
  src/components/common/program/filter/FilterSideBar.tsx
  src/components/common/program/pagination/MuiPagination.tsx
  src/components/common/program/pagination/mui-theme.ts
  src/components/common/program/programs/card/ClosedCard.module.scss
  src/components/common/program/programs/card/EmptyCardList.tsx
  src/components/common/program/programs/card/ProgramArticle.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/program/programs/card/ProgramCardRegacy.tsx
  src/components/common/program/programs/card/ProgramStatusTag.tsx
  src/components/common/program/programs/menu/MenuIcon.tsx
  src/components/common/program/programs/menu/ProgramMenu.tsx
  src/interfaces/Banner.interface.ts
  src/interfaces/Program.interface.ts
  src/interfaces/interface.ts
  src/pages/common/program/Programs.tsx
  src/pages/common/program/regacy/Programs.tsx
  src/reducers/filterReducer.ts
  src/reducers/missionReducer.ts
  src/utils/convert.ts
  src/utils/programConst.ts
  tsconfig.json
Labels: feat

#559 [#558] QA 전 수정사항 반영
  src/Router.tsx
  src/components/admin/program/program-user/table-content/TableBody.tsx
  src/components/admin/program/program-user/table-content/TableHead.tsx
  src/components/admin/program/program-user/table-content/TableRow.tsx
  src/components/admin/program/programs/table-content/TableBody.tsx
  src/components/admin/program/ui/editor-section/FeeSection.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/common/auth/ui/CheckBox.tsx
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/apply/section/PayInfoSection.tsx
  src/components/common/program/program-detail/apply/section/PriceSection.tsx
  src/components/common/program/program-detail/apply/section/UserInputSection.tsx
  src/components/common/program/program-detail/faq/FAQToggle.tsx
  src/components/common/program/program-detail/header/Header.tsx
  src/components/common/program/program-detail/review/ReviewItem.tsx
  src/components/common/program/program-detail/section/ApplySection.tsx
  src/components/common/program/program-detail/section/TabSection.tsx
  src/components/common/program/program-detail/tab/tab-content/FAQTabContent.tsx
  src/components/common/program/program-detail/tab/tab-content/ReviewTabContent.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/pages/admin/program/ProgramCreate.tsx
  src/pages/admin/program/ProgramEdit.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/program/ProgramUsers.tsx
  src/pages/admin/program/Programs.tsx
  src/pages/common/program/ProgramDetail.tsx
  src/utils/convert.ts
Labels: feat

#561 [#560] QA 직전 최종 수정하기
  src/Router.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/common/mypage/review/section/DoneSection.tsx
  src/components/common/mypage/ui/card/root/ApplicationCard.tsx
  src/components/common/review/score/StarScore.tsx
  src/components/common/review/score/TenScore.tsx
  src/components/common/review/score/YesNoScore.tsx
  src/components/common/review/section/ConfirmSection.tsx
  src/components/common/review/section/StarScoreSection.tsx
  src/components/common/review/section/TenScroeSection.tsx
  src/components/common/review/section/TextAreaSection.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/common/mypage/Application.tsx
  src/pages/common/mypage/Review.tsx
  src/pages/common/review/ReviewCreate.tsx
Labels: feat

#563 [#562] 프로그램 페이지 1차 QA 반영
  public/icons/checkbox-checked-tag.svg
  public/icons/document.svg
  public/icons/mingcute_celebrate-fill.svg
  public/icons/search-eye-line.svg
  src/components/common/program/filter/FilterCheckbox.tsx
  src/components/common/program/filter/FilterSideBar.tsx
  src/components/common/program/pagination/MuiPagination.tsx
  src/components/common/program/programs/card/EmptyCardList.tsx
  src/components/common/program/programs/card/ProgramArticle.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/program/programs/card/ProgramClassificationTag.tsx
  src/components/common/program/programs/card/ProgramStatusTag.tsx
  src/components/common/program/programs/menu/MenuIcon.tsx
  src/components/common/program/programs/menu/ProgramMenu.tsx
  src/interfaces/Program.interface.ts
  src/interfaces/interface.ts
  src/pages/common/program/Programs.tsx
  src/utils/programConst.ts
Labels: feat, fix

#566 [ #565] 프로그램 개설 오류 수정
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/utils/convert.ts
Labels: fix

#567 [#564] 프로그램 페이지 2차 QA 반영
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/filter/FilterSideBar.tsx
  src/components/common/program/programs/card/EmptyCardList.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/pages/common/program/Programs.tsx
Labels: fix

#573 [#572] 배너 타이틀 19기로 변경
  src/components/common/home/regacy/header/HomeHeader.tsx
Labels: design

#574 [#572] 배너 타이틀 19기로 변경
  src/components/common/home/regacy/header/HomeHeader.tsx
Labels: design

#575 [#570] 1차 QA 수정사항 반영
  public/icons/circle-checked.svg
  public/icons/circle-unchecked.svg
  src/components/admin/program/programs/table-content/TableBody.tsx
  src/components/admin/program/ui/editor/FAQEditor.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/common/program/program-detail/apply/content/CautionContent.tsx
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
  src/components/common/program/program-detail/apply/section/UserInputSection.tsx
  src/components/common/program/program-detail/section/ApplySection.tsx
  src/components/common/program/program-detail/tab/tab-content/DetailTabContent.tsx
  src/components/common/program/program-detail/tab/tab-content/ReviewTabContent.tsx
  src/components/common/program/program-detail/toggle/DateToggle.tsx
  src/components/common/ui/input/TextArea.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/program/Programs.tsx
Labels: feat, design, fix

#577 [#576] 어드민 후기 관리 페이지 제작
  package-lock.json
  package.json
  src/App.tsx
  src/components/admin/program/ui/editor/FAQEditor.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/admin/review/review-detail/table-content/TableBody.tsx
  src/components/admin/review/review-detail/table-content/TableHead.tsx
  src/components/admin/review/reviews/table-content/TableBody.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/apply/section/PayInfoSection.tsx
  src/components/common/program/program-detail/toggle/DateToggle.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/review/Reviews.tsx
  src/pages/admin/review/ReviewsDetail.tsx
Labels: feat, design

#585 [#584] 어드민 QA 전 마무리 1차
  src/components/admin/banner/main-banner/MainBannerInputContent.tsx
  src/components/admin/banner/pop-up-banner/PopUpBannerInputContent.tsx
  src/components/admin/banner/program-banner/ProgramBannerInputContent.tsx
  src/components/admin/banner/top-bar-banner/TopBarBannerInputContent.tsx
  src/components/admin/coupon/CouponEditor.tsx
  src/components/admin/program/programs/table-content/TableBody.tsx
  src/components/admin/program/ui/editor/FAQEditor.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/admin/review/review-detail/table-content/TableBody.tsx
  src/components/admin/review/review-detail/table-content/TableHead.tsx
  src/components/admin/review/reviews/table-content/TableBody.tsx
  src/components/admin/user/users/table-content/TableBody.tsx
  src/components/admin/user/users/table-content/TableHead.tsx
  src/pages/admin/banner/main-banner/MainBannerCreate.tsx
  src/pages/admin/banner/main-banner/MainBannerEdit.tsx
  src/pages/admin/banner/main-banner/MainBanners.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerCreate.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerEdit.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBanners.tsx
  src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
  src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
  src/pages/admin/banner/program-banner/ProgramBanners.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerCreate.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerEdit.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBanners.tsx
  src/pages/admin/coupon/Coupons.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/program/Programs.tsx
  src/pages/admin/review/Reviews.tsx
  src/pages/admin/user/Users.module.scss
  src/pages/admin/user/Users.tsx
  src/pages/common/mypage/Application.tsx
  src/pages/common/mypage/Review.tsx
  src/utils/convert.ts
Labels: feat

#587 [#580] 홈 화면 재개편
  public/icons/Caret_Circle_Left.svg
  public/icons/Caret_Circle_Right.svg
  public/icons/Chevron_Left_MD.svg
  public/icons/Chevron_Right_MD.svg
  public/icons/Close_MD.svg
  public/icons/Close_SM.svg
  public/icons/megaphone-line.svg
  public/images/home/blog-default-thumbnail.png
  public/images/home/home-program-default.png
  public/images/home/intro1.png
  public/images/home/intro2.png
  public/images/home/intro3.png
  public/images/home/intro4.png
  public/images/home/program-cell.png
  public/images/home/program-thumbnail.png
  public/logo/letscareer-logo-simple.png
  public/logo/letscareer-logo.png
  public/logo/logo-simple.svg
  public/logo/logo.svg
  src/Router.tsx
  src/components/common/home/new/advantage/AdvantageSection.tsx
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/banner/BannerPlay.tsx
  src/components/common/home/new/banner/TopBanner.tsx
  src/components/common/home/new/overview/ProgramListItem.tsx
  src/components/common/home/new/overview/ProgramOverviewListItem.tsx
  src/components/common/home/new/overview/ProgramOverviewSection.tsx
  src/components/common/home/new/pass-review/PassReviewSection.tsx
  src/components/common/home/new/program/ProgramGridItem.tsx
  src/components/common/home/new/program/ProgramPointItem.tsx
  src/components/common/home/new/program/ProgramSection.tsx
  src/components/common/home/new/review/ReviewSection.tsx
  src/components/common/home/new/ui/Description.tsx
  src/components/common/home/new/ui/Heading.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/ui/layout/Layout.tsx
  src/components/common/ui/layout/LayoutRegacy.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/Notice.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/interfaces/Banner.interface.ts
  src/interfaces/Program.interface.ts
  src/pages/common/home/Home.tsx
Labels: feat

#589 [#586] 배너 수정 기능 완성
  src/App.tsx
  src/components/admin/banner/main-banner/MainBannerInputContent.tsx
  src/components/admin/banner/pop-up-banner/PopUpBannerInputContent.tsx
  src/components/admin/banner/program-banner/ProgramBannerInputContent.tsx
  src/components/admin/banner/top-bar-banner/TopBarBannerInputContent.tsx
  src/components/admin/review/review-detail/table-content/TableBody.tsx
  src/pages/admin/banner/main-banner/MainBannerCreate.tsx
  src/pages/admin/banner/main-banner/MainBannerEdit.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerCreate.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerEdit.tsx
  src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
  src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerCreate.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerEdit.tsx
  src/pages/admin/review/ReviewsDetail.tsx
Labels: feat

#591 [#!590] 어드민 QA 전 마무리 2차
  src/components/admin/program/programs/table-content/TableBody.tsx
  src/components/admin/review/reviews/table-content/TableBody.tsx
  src/components/admin/ui/button/ActionButton.tsx
  src/components/admin/user/users/table-content/TableBody.tsx
  src/pages/admin/banner/main-banner/MainBanners.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBanners.tsx
  src/pages/admin/banner/program-banner/ProgramBanners.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBanners.tsx
  src/pages/admin/coupon/Coupons.tsx
  src/pages/admin/program/Programs.tsx
  src/pages/admin/review/Reviews.tsx
  src/pages/admin/review/ReviewsDetail.tsx
  src/pages/admin/user/Users.tsx
Labels: feat

#593 [#592] 홈 화면 api 연동 및 날짜 상태 관리
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/banner/TopBanner.tsx
  src/components/common/home/new/overview/ProgramOverviewListItem.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/interfaces/Banner.interface.ts
Labels: feat

#601 [#600] 프로그램 신청완료 상태 반영 안되는 오류 수정
  src/components/common/program/program-detail/section/ApplySection.tsx
Labels: fix

#602 [Feat] 쿠폰 api 적용 및 프로그램 신청시 데이터 추가 반영
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/apply/section/CouponSection.tsx
  src/components/common/program/program-detail/apply/section/PriceSection.tsx
  src/components/common/program/program-detail/section/ApplySection.tsx
Labels: feat

#610 [#609] 어드민 모바일 배너 이미지 업로드 기능 추가
  src/components/admin/banner/main-banner/MainBannerInputContent.tsx
  src/components/admin/banner/pop-up-banner/PopUpBannerInputContent.tsx
  src/components/admin/banner/program-banner/ProgramBannerInputContent.tsx
  src/interfaces/Banner.interface.ts
  src/pages/admin/banner/main-banner/MainBannerCreate.tsx
  src/pages/admin/banner/main-banner/MainBannerEdit.tsx
  src/pages/admin/banner/main-banner/MainBanners.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerCreate.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBannerEdit.tsx
  src/pages/admin/banner/pop-up-banner/PopUpBanners.tsx
  src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
  src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
  src/pages/admin/banner/program-banner/ProgramBanners.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerCreate.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBannerEdit.tsx
  src/pages/admin/banner/top-bar-banner/TopBarBanners.tsx
Labels: feat

#612 [#582] 프로그램 페이지 수정 사항
  src/components/common/home/new/program/ProgramGridItem.tsx
  src/components/common/home/new/program/ProgramPointItem.tsx
  src/components/common/home/new/program/ProgramSection.tsx
  src/components/common/program/filter/FilterCheckbox.tsx
  src/pages/common/program/Programs.tsx
  src/reducers/filterReducer.ts
  src/utils/programConst.ts
Labels: fix

#626 [Feat] 프로그램 상세 리뷰 조회 api 연동 수정
  src/components/common/program/program-detail/tab/tab-content/ReviewTabContent.tsx
Labels: feat

#629 [#597] 프로그램 상세 페이지 QA 수정사항 (240620)
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/apply/section/CouponSection.tsx
  src/components/common/program/program-detail/apply/section/PriceSection.tsx
  src/components/common/program/program-detail/section/MobileApplySection.tsx
  src/pages/common/program/ProgramDetail.tsx
Labels: fix

#631 [#630] 챌린지 어드민 2차 QA 수정사항 반영
  src/components/admin/challenge/home/section/GuideSection.tsx
  src/components/admin/challenge/home/section/NoticeSection.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
  src/pages/admin/challenge/ChallengeContents.tsx
  src/pages/admin/challenge/ChallengeMissionManagement.tsx
  src/pages/admin/challenge/ChallengeOperationHome.tsx
  src/pages/admin/challenge/ChallengeOperationPayback.tsx
  src/pages/common/mypage/Application.tsx
Labels: fix

#633 [#632] 챌린지 어드민 미션 관리 수정 아이콘 안 보이는 오류 수정
  src/pages/admin/challenge/ChallengeMissionManagement.tsx
Labels: fix

#636 [#635] 어드민 챌린지 제외 QA 수정사항 반영
  src/components/admin/program/program-user/bottom-action/BottomAction.tsx
  src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
  src/components/admin/program/program-user/table-content/TableRow.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/common/mypage/application/section/CompleteSection.tsx
  src/components/common/mypage/application/section/ParticipateSection.tsx
  src/components/common/mypage/ui/card/root/ApplicationCard.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/program/ProgramUsers.tsx
  src/pages/admin/review/Reviews.tsx
  src/pages/common/mypage/Review.tsx
Labels: fix

#637 [#635] 챌린지 가이드 섹션 디자인 변경
  src/components/common/challenge/dashboard/section/GuideSection.tsx
  src/components/common/challenge/dashboard/section/NoticeSection.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/pages/common/challenge/ChallengeDashboard.tsx
Labels: design

#643 [#638] 챌린지 대시보드 입장 추가입력 페이지 제작
  src/Router.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/ui/layout/ChallengeLayout.tsx
  src/components/common/mypage/privacy/form-control/BankDropdown.tsx
  src/pages/common/challenge/ChallengeUserInfo.tsx
  src/pages/common/mypage/Privacy.tsx
Labels: feat, design

#645 [#644] 프로그램 어드민 입금 예정 날짜 관련 오류 수정
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
Labels: fix

#647 [#640] 홈 화면 수정 사항 반영
  public/images/home/company/YBM.png
  public/images/home/company/catch-table.png
  public/images/home/company/cj-fresh.png
  public/images/home/company/hive.svg
  public/images/home/company/humax.svg
  public/images/home/company/hyundai.svg
  public/images/home/company/lg.avif
  public/images/home/company/line.png
  public/images/home/company/naver-cloud.png
  public/images/home/company/naver-webtoon.png
  public/images/home/company/nuvilab.png
  public/images/home/company/pwc.png
  public/images/home/company/samsung-bio.png
  public/images/home/company/sparta.png
  public/images/home/company/under-dogs.png
  public/images/home/company/wadiz.png
  src/components/common/home/new/pass-review/PassReviewSection.tsx
  src/components/common/home/new/program/ProgramSection.tsx
Labels: feat

#652 [#651] 웹사이트 점검 페이지 제작 (main)
  public/images/maintenance/maintenance.png
  src/Router.tsx
  src/components/common/ui/layout/Layout.tsx
  src/pages/maintenance/Maintenance.tsx
Labels: feat, design

#655 [#654] 어드민 웹사이트 점검 페이지 추가
  src/components/admin/ui/layout/AdminLayout.tsx
Labels: fix

#657 [#656] 최종 QA 수정사항 반영
  src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
  src/components/admin/program/program-user/table-content/TableBody.tsx
  src/components/admin/program/program-user/table-content/TableRow.tsx
  src/components/admin/program/ui/editor/ProgramInputContent.tsx
  src/components/common/challenge/ui/layout/ChallengeLayout.tsx
  src/pages/admin/challenge/ChallengeOperationRegisterMission.tsx
  src/pages/admin/program/ProgramEditor.tsx
  src/pages/admin/program/ProgramUsers.tsx
  src/pages/admin/user/Users.tsx
  src/pages/common/challenge/ChallengeDashboard.tsx
  src/pages/common/challenge/ChallengeUserInfo.tsx
Labels: feat, design

#666 [#661] QA 수정사항 반영
  src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
  src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
  src/components/admin/challenge/submit-check/table/table-body/ChallengeSubmitDetail.tsx
  src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
  src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
  src/components/common/mypage/ui/button/LinkButton.tsx
  src/components/common/mypage/ui/card/root/ApplicationCard.tsx
  src/pages/admin/challenge/ChallengeOperationAttendances.tsx
  src/pages/admin/challenge/ChallengeOperationParticipants.tsx
  src/pages/common/challenge/ChallengeDashboard.tsx
  src/utils/convert.ts
Labels: fix

#667 [#665] 최종 QA 수정사항 (240622) - 프로그램 페이지
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/pages/common/program/ProgramDetail.tsx
Labels: feat, fix

#669 [#668] 챌린지 종료 관련 로직 수정
  src/pages/common/challenge/ChallengeDashboard.tsx
  src/pages/common/challenge/MyChallengeDashboard.tsx
Labels: fix

#672 [#671] 챌린지 링크 제출 후 수정하기 버튼 뜨도록 수정
  src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
Labels: fix

#679 [#678] 마지막 수정사항 반영
  public/images/home/company/lg.avif
  public/images/home/company/lg.png
  public/images/home/company/naver-cloud.png
  public/images/home/company/naver-webtoon.png
  public/images/home/company/under-dogs.png
  public/images/home/company/underdogs.png
  public/images/home/review_cj.png
  public/images/home/review_hybe.png
  public/images/home/review_naver_webtoon.png
  public/images/home/review_samsung.png
  public/index.html
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/overview/ProgramListItemContainer.tsx
  src/components/common/home/new/overview/ProgramOverviewListItem.tsx
  src/components/common/home/new/overview/ProgramOverviewSection.tsx
  src/components/common/home/new/pass-review/LogoGroup.tsx
  src/components/common/home/new/pass-review/PassReviewSection.tsx
  src/components/common/home/new/program/ProgramGridItem.tsx
  src/components/common/home/new/program/ProgramSection.tsx
  src/components/common/home/new/ui/Description.tsx
  src/components/common/home/new/ui/Heading.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/button/FilledButton.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/MenuLink.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/components/common/ui/layout/nav/SideNavItem.tsx
  src/components/common/ui/loading/LoadingContainer.tsx
  src/pages/common/program/ProgramDetail.tsx
  src/pages/common/program/Programs.tsx
Labels: fix

#681 [#680] favicon 설정
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon copy.ico
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/manifest copy.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/components/common/home/new/review/ReviewSection.tsx
Labels: design

#684 [#651] 웹사이트 점검 페이지 제작
  public/images/maintenance/maintenance.png
  src/Router.tsx
  src/components/common/ui/layout/Layout.tsx
  src/pages/maintenance/Maintenance.tsx
Labels: feat, design

#685 [#654] 어드민 웹사이트 점검 페이지 추가
  src/components/admin/ui/layout/AdminLayout.tsx
Labels: feat, design

#687 [#686] 웹사이트 점검 페이지 제거
  src/components/admin/ui/layout/AdminLayout.tsx
  src/components/common/ui/layout/Layout.tsx
Labels: feat

#689 [#688] 점검 페이지 제거된 화면 main에 반영 및 배포
  src/components/admin/ui/layout/AdminLayout.tsx
  src/components/common/ui/layout/Layout.tsx
Labels: release

#691 [#690] 결제 정보 모달 표시 오류 수정
  src/components/common/mypage/ui/modal/PriceInfoModal.tsx
Labels: fix

#692 [#690] 결제 정보 모달 표시 오류 수정
  src/components/common/mypage/ui/modal/PriceInfoModal.tsx
Labels: fix

#708 [#707] GA 클래스 세팅
  public/index.html
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/banner/TopBanner.tsx
  src/components/common/home/new/overview/EmptyListItemContainer.tsx
  src/components/common/home/new/overview/ProgramListItemContainer.tsx
  src/components/common/home/new/program/ProgramGridItem.tsx
  src/components/common/home/new/program/ProgramSection.tsx
  src/components/common/home/new/review/ReviewSection.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/components/common/mypage/ui/card/root/ApplicationCard.tsx
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/filter/FilterCheckbox.tsx
  src/components/common/program/filter/FilterSideBar.tsx
  src/components/common/program/program-detail/apply/content/CautionContent.tsx
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/button/NotiButton.tsx
  src/components/common/program/program-detail/tab/tab-bar/TabBar.tsx
  src/components/common/program/programs/card/EmptyCardList.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/review/section/ConfirmSection.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/Icon.tsx
  src/components/common/ui/layout/footer/MenuLink.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/components/common/ui/layout/nav/SideNavItem.tsx
  src/interfaces/Program.interface.ts
  src/pages/common/program/ProgramDetail.tsx
  src/utils/axios.ts
Labels: config

#709 [#707] GA 클래스 세팅
  public/index.html
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/banner/TopBanner.tsx
  src/components/common/home/new/overview/EmptyListItemContainer.tsx
  src/components/common/home/new/overview/ProgramListItemContainer.tsx
  src/components/common/home/new/program/ProgramGridItem.tsx
  src/components/common/home/new/program/ProgramSection.tsx
  src/components/common/home/new/review/ReviewSection.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/components/common/mypage/ui/card/root/ApplicationCard.tsx
  src/components/common/program/banner/Banner.tsx
  src/components/common/program/filter/FilterCheckbox.tsx
  src/components/common/program/filter/FilterSideBar.tsx
  src/components/common/program/program-detail/apply/content/CautionContent.tsx
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/components/common/program/program-detail/apply/content/OverviewContent.tsx
  src/components/common/program/program-detail/apply/content/PayContent.tsx
  src/components/common/program/program-detail/button/NotiButton.tsx
  src/components/common/program/program-detail/tab/tab-bar/TabBar.tsx
  src/components/common/program/programs/card/EmptyCardList.tsx
  src/components/common/program/programs/card/ProgramCard.tsx
  src/components/common/review/section/ConfirmSection.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/Icon.tsx
  src/components/common/ui/layout/footer/MenuLink.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/components/common/ui/layout/nav/SideNavItem.tsx
  src/interfaces/Program.interface.ts
  src/pages/common/program/ProgramDetail.tsx
  src/utils/axios.ts
Labels: config

#711 [#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정
  src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
  src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx
Labels: fix

#712 [#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정
  src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
  src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx
Labels: fix

#716 Revert "[#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정"
  src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
  src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx
Labels: fix

#717 Revert "[#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정"
  src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
  src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx
Labels: fix

#725 [#723] 필터 선택 시 GA 잡히도록 수정
  src/components/common/program/filter/FilterSideBar.tsx
Labels: config

#726 [#723] 필터 선택 시 GA 잡히도록 수정
  src/components/common/program/filter/FilterSideBar.tsx
Labels: config

#724 [#722] 신청폼 화면에서 닫을 수 있는 버튼 추가 - 모바일
  src/components/common/program/program-detail/apply/content/InputContent.tsx
  src/pages/common/program/ProgramDetail.tsx
  src/utils/programConst.ts
Labels: design, fix

#728 [#727] 홈페이지 배너 오류 수정 (main)
  src/components/common/home/new/banner/Banner.tsx
  src/pages/admin/coupon/Coupons.tsx
Labels: fix

#729 [#727] 홈페이지 배너 오류 수정 (develop)
  src/components/common/home/new/banner/Banner.tsx
  src/pages/admin/coupon/Coupons.tsx
Labels: fix

#734 [#733] 배너 클릭시 내부링크면 기존 탭에서 열리고, 외부링크면 새로운 탭에서 열기
  src/Router.tsx
  src/components/common/home/new/banner/Banner.tsx
  src/components/common/home/new/banner/TopBanner.tsx
  src/components/common/home/new/ui/Popup.tsx
  src/components/common/program/banner/Banner.tsx
  src/pages/common/home/HomeRegacy.tsx
  src/pages/common/program/Programs.tsx
Labels: fix

#736 [#735] 비회원 리뷰 이름 마스킹 삭제
  src/components/common/program/program-detail/review/ReviewItem.tsx
Labels: fix

#739 [#738] 후기 별점 삭제
  src/components/common/program/program-detail/review/ReviewItem.tsx
  src/pages/admin/challenge/ChallengeOperationPayback.tsx
Labels: fix

#740 [#738] 후기 별점 삭제
  src/components/common/program/program-detail/review/ReviewItem.tsx
  src/pages/admin/challenge/ChallengeOperationPayback.tsx
Labels: fix
