Repository Let-s-intern/lets-intern-client, pull requests merged in 2024-05, with the labels that each got.

#490 [#486] 챌린지 대시보드 기능 추가
  package-lock.json
  public/images/mission-date-question-image.svg
  src/components/common/challenge/dashboard/section/MissionSection.tsx
  src/components/common/challenge/dashboard/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
  src/interfaces/Program.interface.ts
  src/interfaces/interface.ts
Labels: feat

#493 [#492] 어드민 프로그램 참여자 페이지 사용성 개선
  src/components/admin/challenge/user/table/top-action-group/DownloadButtonGroup.tsx
  src/components/admin/program/program-user/bottom-action/BottomAction.tsx
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
  src/components/admin/program/program-user/table-content/TableHead.tsx
  src/components/admin/ui/table/regacy/TH.tsx
  src/pages/admin/program/ProgramUsers.module.scss
  src/pages/admin/program/ProgramUsers.tsx
Labels: feat

#498 [#497] 챌린지 어드민 제출확인 20행만 나오는 오류 수정
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
Labels: fix

#499 Revert "[#497] 챌린지 어드민 제출확인 20행만 나오는 오류 수정"
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
Labels: revert

#502 [#496] CSV 다운로드 시 입금 예정 금액 행 나누어지는 오류 수정
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
Labels: fix

#505 [#496] 프로그램 참여자 csv 다운로드 오류 수정
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
Labels: fix

#506 [#494] 챌린지 대시보드 기능 추가 (main)
  package-lock.json
  public/icons/nav-icon.svg
  public/icons/user-circle.svg
  public/images/mission-date-question-image.svg
  public/logo/letscareer-logo-simple.png
  public/logo/letscareer-logo.png
  src/components/common/challenge/dashboard/section/MissionSection.tsx
  src/components/common/challenge/dashboard/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
  src/components/common/ui/layout/Footer.tsx
  src/components/common/ui/layout/Layout.tsx
  src/components/common/ui/layout/footer/DocumentLink.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/Icon.tsx
  src/components/common/ui/layout/footer/MenuLink.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/components/common/ui/layout/nav/NavItem.tsx
  src/components/common/ui/layout/nav/SideNavItem.tsx
  src/components/common/ui/tab/TabItem.tsx
  src/index.css
  src/interfaces/Program.interface.ts
  src/interfaces/interface.ts
  src/pages/common/program/Programs.module.scss
Labels: feat

#518 [#509] 메인 브랜치에 챌린지 대시보드 기능 반영
  public/images/mission-date-question-image.svg
  src/components/common/challenge/dashboard/section/MissionSection.tsx
  src/components/common/challenge/dashboard/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
  src/interfaces/Program.interface.ts
  src/interfaces/interface.ts
Labels: release

#522 [#521] 어드민 프로그램 및 프로그램 참여자 페이지 열 수정 및 순서 변경
  src/components/admin/program/program-user/table-content/TableHead.tsx
  src/components/admin/program/program-user/table-content/TableRow.tsx
  src/components/admin/program/programs/table-content/TableBody.tsx
  src/components/admin/program/programs/table-content/TableHead.tsx
  src/pages/admin/program/ProgramUsers.tsx
  src/utils/convert.ts
Labels: design

#524 [#523] 어드민 프로그램 개설 입력 폼 변경
  src/components/admin/program/ui/editor-section/ProgramTypeSection.tsx
  src/components/admin/program/ui/editor/ProgramEditor.tsx
Labels: design

#526 [#525] 메인 배포 페이지 수정사항 반영 (main)
  src/components/admin/challenge/mission/mission-contents/table/table-body/TableBody.tsx
  src/components/common/home/regacy/header/HomeHeader.tsx
  src/pages/admin/program/ProgramUsers.tsx
  src/pages/common/home/HomeRegacy.tsx
Labels: fix

#527 [#525] 메인 배포 페이지 수정사항 반영 (develop)
  src/components/admin/challenge/mission/mission-contents/table/table-body/TableBody.tsx
  src/components/common/home/regacy/header/HomeHeader.tsx
  src/pages/common/home/HomeRegacy.tsx
Labels: fix

#529 [#528] 회원 API 및 프로그램 개설 API 교체
  src/components/admin/program/ui/editor/ProgramEditor.tsx
  src/components/common/ui/layout/NavBar.tsx
  src/pages/admin/program/ProgramCreate.tsx
  src/pages/admin/program/Programs.tsx
  src/pages/common/auth/Login.tsx
  src/pages/common/auth/SignUp.tsx
  src/utils/convert.ts
Labels: feat

#534 [#533] 유저 정보와 관리자 확인 API 교체
  src/components/admin/ui/layout/AdminLayout.tsx
  src/components/common/ui/layout/NavBar.tsx
  src/pages/admin/program/Programs.tsx
Labels: fix

#530 [#517] 챌린지 가이드 게시판 추가
  src/components/admin/challenge/home/item/GuideItem.tsx
  src/components/admin/challenge/home/section/GuideSection.tsx
  src/components/admin/challenge/home/section/MissionDateSection.tsx
  src/components/admin/challenge/home/section/NoticeSection.tsx
  src/components/admin/challenge/ui/modal/GuideEditorModal.tsx
  src/components/admin/challenge/ui/modal/InputBox.tsx
  src/interfaces/Guide.interface.ts
  src/interfaces/interface.ts
  src/pages/admin/challenge/ChallengeHome.tsx
Labels: feat

#532 [#520] 미션 등록 / 미션 템플릿 테이블 추가
  src/Router.tsx
  src/components/admin/challenge/mission/mission/table/table-body/NewTableBodyRow.tsx
  src/components/admin/challenge/ui/layout/ChallengeAdminLayout.tsx
  src/components/admin/challenge/ui/lineTable/DropdownCell.tsx
  src/components/admin/challenge/ui/lineTable/LineTableBody.tsx
  src/components/admin/challenge/ui/lineTable/LineTableBodyCell.tsx
  src/components/admin/challenge/ui/lineTable/LineTableBodyRow.tsx
  src/components/admin/challenge/ui/lineTable/LineTableHead.tsx
  src/components/admin/challenge/ui/lineTable/TextareaCell.tsx
  src/components/admin/challenge/ui/table/table-head/TableHeadCell.tsx
  src/components/admin/ui/layout/AdminLayout.tsx
  src/interfaces/Mission.interface.ts
  src/interfaces/interface.ts
  src/pages/admin/challenge/ChallengeMission.tsx
  src/pages/admin/challenge/ChallengeMissionManagement.tsx
  src/pages/admin/challenge/ChallengeMissionRegacy.tsx
  src/reducers/missionReducer.ts
  src/reducers/missionTemplateReducer.ts
  src/utils/convert.ts
  src/utils/formatDateString.ts
  src/utils/tableCellWidthList.ts
Labels: feat

#531 [#519] 참여자 리스트 노출 변경
  src/components/admin/challenge/user/table/table-body/TableRowContent.tsx
  src/components/admin/challenge/user/table/table-head/TableHead.tsx
  src/interfaces/Application.interface.ts
  src/interfaces/interface.ts
  src/utils/tableCellWidthList.ts
Labels: feat

#537 [#536] 챌린지 대시보드 임시 개편 및 오류 수정
  src/components/admin/challenge/home/item/MissionDateItem.tsx
  src/components/admin/challenge/home/item/MissionResultItem.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableBodyRow.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowContent.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowDetailMenu.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowEditorMenu.tsx
  src/components/admin/challenge/submit-check/table/table-body/TableRowContent.tsx
  src/components/admin/challenge/ui/dropdown/home/TopDropdown.tsx
  src/components/admin/program/program-user/bottom-action/BottomAction.tsx
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionCalendarItem.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionNotStartedIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/dashboard/section/DailyMissionSection.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionNotStartedIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
  src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
  src/components/common/challenge/my-challenge/mission/YetMissionItem.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSection.tsx
  src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
  src/components/common/home/regacy/header/HomeHeader.tsx
  src/pages/admin/program/ProgramUsers.tsx
Labels: feat

#538 [#536] 챌린지 대시보드 임시 개편 (develop)
  src/components/admin/challenge/home/item/MissionDateItem.tsx
  src/components/admin/challenge/home/item/MissionResultItem.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableBodyRow.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowContent.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowDetailMenu.tsx
  src/components/admin/challenge/mission/mission/table/table-body/TableRowEditorMenu.tsx
  src/components/admin/challenge/submit-check/table/table-body/TableRowContent.tsx
  src/components/admin/challenge/ui/dropdown/home/TopDropdown.tsx
  src/components/admin/program/program-user/bottom-action/BottomAction.tsx
  src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionCalendarItem.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionNotStartedIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/dashboard/section/DailyMissionSection.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionNotStartedIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
  src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
  src/components/common/challenge/my-challenge/mission/YetMissionItem.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionSection.tsx
  src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
  src/components/common/home/regacy/header/HomeHeader.tsx
  src/pages/admin/program/ProgramUsers.tsx
Labels: feat

#540 [#539] 챌린지 대시보드 임시 개편 마무리
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionInfoSection.tsx
  src/pages/common/challenge/ChallengeDashboard.tsx
Labels: feat

#541 [#539] 챌린지 대시보드 임시 개편 마무리
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/section/DailyMissionInfoSection.tsx
  src/pages/common/challenge/ChallengeDashboard.tsx
Labels: feat

#543 [#542] 챌린지 대시보드 임시 개편 QA 수정사항 반영
  public/images/mission-date-question-image.svg
  src/components/admin/challenge/mission/mission/dropdown/AdditionalDropdown.tsx
  src/components/admin/challenge/mission/mission/dropdown/EssentialDropdown.tsx
  src/components/admin/challenge/mission/mission/dropdown/LimitedDropdown.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/dashboard/section/MissionSection.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
  src/components/common/challenge/my-challenge/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/ui/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/ui/tooltip-question/ScoreTooltipQuestion.tsx
  src/utils/convert.ts
Labels: fix

#544 [#542] 챌린지 대시보드 임시 개편 QA 수정사항 반영 (develop)
  public/images/mission-date-question-image.svg
  src/components/admin/challenge/mission/mission/dropdown/AdditionalDropdown.tsx
  src/components/admin/challenge/mission/mission/dropdown/EssentialDropdown.tsx
  src/components/admin/challenge/mission/mission/dropdown/LimitedDropdown.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/dashboard/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/dashboard/section/MissionSection.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
  src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
  src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
  src/components/common/challenge/my-challenge/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/ui/tooltip-question/MissionTooltipQuestion.tsx
  src/components/common/challenge/ui/tooltip-question/ScoreTooltipQuestion.tsx
  src/utils/convert.ts
Labels: fix

#546 [#545] 어드민 챌린지 테이블 번호를 회차로 변경
  src/components/admin/challenge/mission/mission/table/table-body/TableBody.tsx
  src/components/admin/challenge/mission/mission/table/table-head/TableHead.tsx
  src/components/admin/challenge/submit-check/table/table-body/TableBody.tsx
  src/components/admin/challenge/submit-check/table/table-head/TableHead.tsx
Labels: design

#547 [#545] 어드민 챌린지 테이블 번호를 회차로 변경
  src/components/admin/challenge/mission/mission/table/table-body/TableBody.tsx
  src/components/admin/challenge/mission/mission/table/table-head/TableHead.tsx
  src/components/admin/challenge/submit-check/table/table-body/TableBody.tsx
  src/components/admin/challenge/submit-check/table/table-head/TableHead.tsx
Labels: feat

#550 [#549] 챌린지 대시보드 일부 항목 숨기기
  src/Router.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/ui/layout/NavBar.tsx
Labels: design

#551 [#549] 챌린지 대시보드 일부 항목 숨기기 (develop)
  src/Router.tsx
  src/components/common/challenge/dashboard/section/ScoreSection.tsx
  src/components/common/challenge/ui/layout/NavBar.tsx
Labels: design

#554 [#535] 마이페이지 개선
  src/Router.tsx
  src/components/common/home/new/ui/Badge.tsx
  src/components/common/mypage/application/section/ApplySection.tsx
  src/components/common/mypage/application/section/CompleteSection.tsx
  src/components/common/mypage/application/section/ParticipateSection.tsx
  src/components/common/mypage/application/style/SectionStyle.tsx
  src/components/common/mypage/privacy/form-control/BankDropdown.tsx
  src/components/common/mypage/privacy/form-control/GradeDropdown.tsx
  src/components/common/mypage/privacy/section/AccountInfo.tsx
  src/components/common/mypage/privacy/section/BasicInfo.tsx
  src/components/common/mypage/privacy/section/ChangePassword.tsx
  src/components/common/mypage/privacy/section/MarketingAgree.tsx
  src/components/common/mypage/regacy/alert/WithDrawAlertModal.module.scss
  src/components/common/mypage/regacy/alert/WithDrawAlertModal.tsx
  src/components/common/mypage/regacy/dropdown/BankDropdown.tsx
  src/components/common/mypage/regacy/section/privacy/AccountInfo.tsx
  src/components/common/mypage/regacy/section/privacy/MainInfo.tsx
  src/components/common/mypage/regacy/section/privacy/PasswordChange.tsx
  src/components/common/mypage/regacy/section/privacy/SubInfo.tsx
  src/components/common/mypage/review/section/DoneSection.tsx
  src/components/common/mypage/review/section/WaitingSection.tsx
  src/components/common/mypage/ui/button/Button.tsx
  src/components/common/mypage/ui/button/LinkButton.tsx
  src/components/common/mypage/ui/card/ApplicationCard.tsx
  src/components/common/program/program-detail/tab/content/ReviewTab.tsx
  src/components/common/review/regacy/card/ApplicationCard.tsx
  src/components/common/review/regacy/card/ReviewCard.tsx
  src/components/common/review/regacy/tooltip-question/TooltipQuestion.tsx
  src/components/common/review/regacy/ui/InputTitle.tsx
  src/components/common/review/regacy/ui/ReviewHeader.tsx
  src/components/common/review/regacy/ui/Star.tsx
  src/components/common/review/regacy/ui/TextArea.tsx
  src/components/common/review/score/StarScore.tsx
  src/components/common/review/score/TenScore.tsx
  src/components/common/review/score/YesNoScore.tsx
  src/components/common/review/section/ConfirmSection.tsx
  src/components/common/review/section/StarScoreSection.tsx
  src/components/common/review/section/TenScroeSection.tsx
  src/components/common/review/section/TextAreaSection.tsx
  src/components/common/ui/input/Input.tsx
  src/components/common/ui/input/TextArea.tsx
  src/pages/common/mypage/Application.tsx
  src/pages/common/mypage/ApplicationRegacy.tsx
  src/pages/common/mypage/MyPage.tsx
  src/pages/common/mypage/Privacy.tsx
  src/pages/common/mypage/PrivacyRegacy.tsx
  src/pages/common/mypage/Review.tsx
  src/pages/common/mypage/ReviewRegacy.tsx
  src/pages/common/review/ReviewCreate.tsx
  src/pages/common/review/ReviewDetail.tsx
  src/pages/common/review/regacy/ReviewCreateRegacy.tsx
  src/utils/convert.ts
  tailwind.config.js
Labels: feat, design

#552 [#548] 미션 템플릿 API 수정
  src/components/admin/challenge/home/section/GuideSection.tsx
  src/components/admin/challenge/home/section/MissionDateSection.tsx
  src/components/admin/challenge/home/section/MissionResultSection.tsx
  src/components/admin/challenge/home/section/NoticeSection.tsx
  src/components/admin/challenge/ui/lineTable/LineTableBodyRow.tsx
  src/pages/admin/challenge/ChallengeMission.tsx
  src/pages/admin/challenge/ChallengeMissionManagement.tsx
  src/reducers/missionTemplateReducer.ts
Labels: fix
