Repository Let-s-intern/lets-intern-client, pull requests merged in 2024-04, with the labels that each got.

#472 [#471] 메인 브랜치에 개발 브랜치 수정사항 반영
  src/components/common/program/program-detail/ui/price/CautionPriceContent.tsx
Labels: release

#476 [#475] 개인정보처리방침 및 서비스이용약관 링크 수정
  src/components/common/auth/modal/PrivacyPolicyModal.tsx
  src/components/common/ui/layout/Footer.tsx
  src/pages/common/auth/SignUp.tsx
Labels: fix

#481 [#480] 어드민 후기 안 보이는 오류 수정
  src/components/admin/review/review-detail/table-content/TableBody.tsx
  src/components/admin/ui/pagination/AdminPagination.tsx
  src/index.css
  src/pages/admin/review/Reviews.module.scss
  src/pages/admin/review/Reviews.tsx
  src/pages/admin/review/ReviewsDetail.module.scss
  src/pages/admin/review/ReviewsDetail.tsx
Labels: fix, refactor

#467 [#440] 네비게이션 바 변경
  public/icons/nav-icon.svg
  public/icons/user-circle.svg
  public/logo/letscareer-logo-simple.png
  public/logo/letscareer-logo.png
  src/components/common/ui/layout/Layout.tsx
  src/components/common/ui/layout/nav/NavBar.tsx
  src/components/common/ui/layout/nav/NavItem.tsx
  src/components/common/ui/layout/nav/SideNavItem.tsx
  src/components/common/ui/tab/TabItem.tsx
  src/pages/common/program/Programs.module.scss
Labels: design, refactor

#482 [#480] 어드민 후기 안 보이는 오류 수정
  src/components/admin/review/review-detail/table-content/TableBody.tsx
  src/components/admin/ui/pagination/AdminPagination.tsx
  src/index.css
  src/pages/admin/review/Reviews.module.scss
  src/pages/admin/review/Reviews.tsx
  src/pages/admin/review/ReviewsDetail.module.scss
  src/pages/admin/review/ReviewsDetail.tsx
Labels: fix, refactor

#484 [#483] Footer 변경
  src/components/common/ui/layout/Footer.tsx
  src/components/common/ui/layout/Layout.tsx
  src/components/common/ui/layout/footer/DocumentLink.tsx
  src/components/common/ui/layout/footer/Footer.tsx
  src/components/common/ui/layout/footer/Icon.tsx
  src/components/common/ui/layout/footer/MenuLink.tsx
  src/index.css
Labels: design, refactor
